Impl get_size::GetSize (behind feature flag) (v2 branch)
servo/rust-smallvec pull request #336
Opened 2024-01-17 16:36 UTC by amandasaurus

Shows memory usage of the struct

cf. issue #331

this is against the `v2` branch. The tests pass, but I haven't tried this code in real uses yet.

2024-01-17 17:19 UTC, mbrubeck requested changes
Looks good, just a couple of minor changes needed.

2024-01-17 17:19 UTC, mbrubeck commented on src/lib.rs
> +impl<A: Array> GetSize for SmallVec<A>
The generic types for SmallVec have changed in `v2`.  This should now be `impl<T, const N: usize>`.

2024-01-17 17:19 UTC, mbrubeck commented on src/tests.rs
> +#[cfg(feature = "get-size")]
This test should be disabled for non-64-bit platforms (similar to #335 except the `"union"` feature does not exist in `v2`).

2024-01-18 12:34 UTC, amandasaurus commented
I've fixed those 2 things, and pushed a new branch.

2024-01-18 20:04 UTC, mbrubeck approved these changes

2024-01-18 20:04 UTC, merged